# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latlong-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LatLong
  template:
    metadata:
      labels:
        app: LatLong
    spec:
      containers:
        - name: app
          image: ghcr.io/beemi/lat-long-service:main
          ports:
            - containerPort: 3000
          env:
            - name: API_ENDPOINT
              value: https://api.postcodes.io
          imagePullPolicy: Always
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: latlong-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: LatLong
